# Generated by Django 5.0 on 2023-12-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота')),
                ('name', models.CharField(max_length=256, verbose_name='название объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'объект на карте',
                'verbose_name_plural': 'объекты на карте',
                'ordering': ('-created_at',),
            },
        ),
    ]
